### PR TITLE
Sample images for sample data

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Till now, there was only one image used in sample data for all articles and modules. This PR adds some images from the NASA imagery to the sampledata. 
Additionally a new Random image module has been added to the right dolumns 
grafik

### CODE REVIEW

**Comment by chmst** [comment]
Different parameters, blog with 1 leading and 2 columns 

Screenshot_2020-09-14 Template

**Comment by brianteeman** [comment]
In the sample data for these images can you please include information for the origin of the images. The images you have selected from nasa are without copyright (which is good) but "NASA should be acknowledged as the source of the material." as stated in the usage guidelines https://www.nasa.gov/multimedia/guidelines/index.html

If you look at the sample data in joomla 3 and how wikipedia is credited that should be a good example to follow.

**Comment by chmst** [comment]
@brianteeman thank you, will do it in the same way as in the testdata plugin when I am back in the evening.

BTW - as I am not a designer, I have asked for advice and maybe the images will be replaced. 
So I make this a draft.

**Comment by chmst** [comment]
Closing this as chnaging images does not need to keep a PR

**Pull request closed without merging**
