### PR TITLE
[Testing] This is a fake PR for testing different work pieces together

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This PR is just a fake PR for testing, i.e. it will not be merged.

It brings together the changes from following PRs and their branches:
- PR #18 "Use local Google Fonts"- branch [4.0-dev-google-fonts-enhancements](https://github.com/joomla/cassiopeia/tree/4.0-dev-google-fonts-enhancements)
- PR #19 "Sample data for Cassiopeia header" - branch [4.0-dev-sample-data-enhancement](https://github.com/joomla/cassiopeia/tree/4.0-dev-sample-data-enhancement)
- PR #46 "Add Metismenu to Cassiopeia, rework Cassiopeia's HTML structure, use relative CSS sizes" - branch [4-0-dev-frontend-metismenu-and-html-structure](https://github.com/joomla/cassiopeia/tree/cassiopeia/4-0-dev-frontend-metismenu-and-html-structure)

Developers of these features, please continue to develop on the branch(es) mentioned above for your work piece(s).

For updating this branch here with your changes for testing, merge then the particular branch of your workpiece into the branch [4.0-dev-testing-metismenu-sampledata-htmlstructure](https://github.com/joomla/cassiopeia/tree/4.0-dev-testing-metismenu-sampledata-htmlstructure) of this fake PR.

How this is to be done depends on your Git client, but normally (e.g. in GitHub Desktop) you check out the branch of this fake PR and then select "Merge into current branch ..." in the menu, and then chose the branch of your workpiece.

### Testing Instructions

Checkout the branch, pull the latest changes and run "npm ci".

Or use the following package to make a new installation:

[https://test5.richard-fath.de/Joomla_4.0.0-beta4-dev-Cassiopeia-Test-Full_Package_2020-08-29_v1.zip](https://test5.richard-fath.de/Joomla_4.0.0-beta4-dev-Cassiopeia-Test-Full_Package_2020-08-29_v1.zip)

Or use the following package to update a current 4.0-dev or latest 4.0 nightly build from 2020-08-29 or a bit earlier, but not too old:

[https://test5.richard-fath.de/Joomla_4.0.0-beta4-dev-Cassiopeia-Test-Update_Package_2020-08-29_v1.zip](https://test5.richard-fath.de/Joomla_4.0.0-beta4-dev-Cassiopeia-Test-Update_Package_2020-08-29_v1.zip)

After that, login to backend and install "Blog Sample Data" to see the metismenu being used in frontend.

### CODE REVIEW

**Comment by richard67** [comment]
Added the local Google Fonts, too.

**Comment by Magnytu2** [comment]
The size of the Yes / No button must be the same as the other two buttons.
The text "Giigle font for text and headings" is split over two lines.
There is only a choice of two fonts. So you have to load them into the template?
The display of the submenu in front does not seem to work. Is there a code to add in the menu module?

**Comment by richard67** [comment]
> The size of the Yes / No button must be the same as the other two buttons.

This is not subject of this PR, as the description clearly sais.

> The text "Giigle font for text and headings" is split over two lines.

This is not subject of this PR, as the description clearly sais.

> There is only a choice of two fonts.

Yes, so what? Without this PR you have only one, and this is loaded from Google fonts, while the 2 added by this PR are stored locally. If not sure what this PR does, read the desacriptions of the single PRs linked in the descipriton of this PR-

> The display of the submenu in front does not seem to work. Is there a code to add in the menu module?

You have to install Blog Sample Data in the backend with use of the corresponding button on the control panel.

Or you have to add manually a menu module at the right position.

Should be easy to see for a Joomla site admin if there is a menu module defined in a particular position, or not?

**Comment by richard67** [comment]
I've added a sentence to the end of the testing instructions, telling to install Blog Sample Data in order to see the metisnemu in use in the frontend.

**Comment by Magnytu2** [comment]
Sorry, if I talk about items that are not in the PR.
For Google Fonts I was just asking for the method to add Google Fonts.
With the installation of the blog example the menu works fine.
To display the submenu, all you have to do is use the Layout> Metismenu and the Tag Module in nav in the module parameters in the "menu" position.

**Comment by richard67** [comment]
Methods to add more Google Fonts in addition to the two which are shipped can be found at the bottom of the description of #18 .

Note that all here is still work in progress, especially design might change.

**Comment by Magnytu2** [comment]
It is very good. That there are only two or three standard fonts is sufficient. I will write the method to add more, in the Joomla documentation.
The most important thing in Cassiopeia is to find at least the same settings as Protostar. To be able to adjust its primary and secondary color and easily add modules in the Header. BUT I know that is not the subject of this PR. Thank you for your work.

**Comment by richard67** [comment]
> I will write the method to add more, in the Joomla documentation.

Please wait with that. When we have finished development in this repository, we will make a PR for the CMS repository.

During all this time, things can still change.

So if you start writing now, it would maybe later be necessary to change that again.

> The most important thing in Cassiopeia is to find at least the same settings as Protostar. To be able to adjust its primary and secondary color and easily add modules in the Header. BUT I know that is not the subject of this PR. Thank you for your work.

We have this on our task list and will sooner or later make PRs in this repo here for that.

**Comment by richard67** [comment]
Most important is: Is the metismenu working well?

**Comment by Magnytu2** [comment]
The metismenu works fine. I am still going to test adding menu and deleting some, modifying the links.

**Comment by richard67** [comment]
> The metismenu works fine. I am still going to test adding menu and deleting some, modifying the links.

@Magnytu2 Great. Please test all different types of meu items, also alias, separator, external URL and whatever else beside "normal" menu items. Thanks for testing so far.

**Comment by Magnytu2** [comment]
Everything seems to work fine with the metismenu menu. It adapts to the length of the menu link titles. I can delete, add and modify their positions without problem.
Accueil-2

**Comment by richard67** [comment]
@Magnytu2 That sounds good. How many levels of sub-menus did you try? Can you try more than what you see here?

metismenu-test-1

I don't have time right now, and I haven't tested yet if it works with more than 3 levels.

Thanks so far for your tests and feedback.

**Comment by Magnytu2** [comment]
Indeed there is a problem. The fourth level is not working.

**Comment by richard67** [comment]
Ok, thanks for that info.

We will investigate.

Maybe it is desired behavior, because a menu with too many levels is not really good UX, and maybe not good a11y (accessibility).

We will see what metismenu documentation says.

**Comment by Magnytu2** [comment]
It is true that three levels are sufficient.

**Comment by Magnytu2** [comment]
In mobile mode, there is a shift that I cannot explain.
Accueil-3

**Comment by richard67** [comment]
Thanks. Will check tomorrow.

**Comment by drmenzelit** [comment]
> In mobile mode, there is a shift that I cannot explain.
We will take this in account, design is still work in progress

**Comment by paternax** [comment]
Most things work fine. I made for example a very long Submenu - this works in desktop and mobile. Also with pictures in the menu items, also with sticky mode. One small point is, that at a width from 974 Pixel you see the hamburger menu and the normal menu:

cassiopeia-menu1

**Comment by drmenzelit** [comment]
@paternax thank you for your comment, we will have a look at the media queries

**Comment by richard67** [comment]
@drmenzelit Shouldn't your last commit go into the metismenu branch? This on here is the one for testing. You can pull to both, or you pull to the metismenu branch and i pull into here, but pull only here doesn't make sense.

**Comment by Magnytu2** [comment]
Good evening, I just quickly did a test with version 4 of Cassiopeia 27082020. Very good logo at the top and the menu below. The Back-to-top button works fine. The change of font too.
I have more problem with the demo menu version. It lacks front links. The width of the articles varies according to the menu links. And the main_top position is displayed while it is empty. There are also missing spaces between fields and buttons, for example Log in.
It's a quick little lap I would do more testing tomorrow morning.

Archive_et_Menus__Items__Main_Menu_Blog__-_Cassiopeia_27082020_-_Administration

**Comment by richard67** [comment]
@Magnytu2 I've just updated here and have built new packages and have updated the links to the packages in the testing instructions. Things look much better now. There was a problem with bringing the other changes together here, but that has been solved.

**Comment by Magnytu2** [comment]
Hello, a quick feedback. All menu links work. I don't really like the display of the submenu. I have a slight preference for the previous version.
We have a difference in width for the display of the articles. The "About" link gives a width that I do not understand. It is the same problem for the display for the "Category list" link.
A space is missing above the "MainManu" module to the right and at the bottom of the "login form" module as well. There is also an offset with the "Filter" button on this page.
Is the title of the "Older Posts" module bigger?
The logo area is too large, or too far from the menu. Because if we fix the header in the backend, there is no more room to display articles.
About

**Comment by richard67** [comment]
@Magnytu2 Thanks for testing and feedback. The design will very likely change, design phase will be finished end of next week, then we will implement the necessary (S)CSS. But regarding functionality you can already see here what we have now, metismenu, local Google fonts, the sample data extensions and structural HTML changes, e.g. use of sections. If that all is ok, we are on a good way.

**Comment by Magnytu2** [comment]
Yes that's great and I can't thank you enough. I sometimes have the difficult comment. Sorry ! But I feel like I'm waiting for Joomla! 4 for far too long.
We will also have the possibility to change the colors in the backend settings?

**Comment by richard67** [comment]
@Magnytu2 No idea about the colors. Maybe someone else knows.

**Comment by richard67** [comment]
Am closing this fake PR and will delete the corresponding testing branch.

For further testing of what has been already done please use the [development](https://github.com/joomla/cassiopeia/tree/development) branch.

For testing further improvements which are not approved yet, there will be separate PRs for testing.

I will soon make a fake PR for the development branch like this one here, with desriptions of the changes, testing instructions and links to packages.

**Pull request closed without merging**
