### PR TITLE
Sample data for Cassiopeia header

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
The main menu has been moved to position menu, layout metismenu.
A first submenu has been added to the menu item " blog", but it i.s hidden until a dropdown is possible

The search form (module search) on position search is visible. 

cassiopeia-header-2

### Testing Instructions
On a clean installation install the blog sample data. 

### Expected result
The Menu looks like the screen above

### Actual result
The main menu is on position top-a and has no submenu items.
cassiopeia-origin

### CODE REVIEW

**Comment by chmst** [comment]
The sample data now provide this menu: 

main-menu-blog

The module is defined with layout "metismenu".

**Comment by brianteeman** [comment]
From my  training a common issue I came across was with my sample data that I used for teaching. Like the sample data here I used the same category for category blog and category list menus.  This causes problems when you drill down into the articles as you end up viewing the article with whichever menu had the lowest id so the modules and menu params are wrong

**Comment by chmst** [comment]
@brianteeman thank you for the hint. 
In general I think that it should be possible to have two links to the same content in different layouts. Sounds more like a routing problem. 

But will work on that in the sample data and avoid confusion.

**Comment by brianteeman** [comment]
Yes it is a routing problem but at the same time its working as designed so best to try and avoid it in the sample data

**Comment by chmst** [comment]
Some changes made in Sample Data:

- The image rain drops removed, the module is still there and can be filled with something more attractive
- A new category "Template" 
- 3 new lorem ipsum articles added to this category
- A new link in the main menu blog to this category for a demo of the modufier classes
- Metis menu blog fixed with meniItem types and links

**Comment by brianteeman** [comment]
Just a suggestion but if you make the three sample articles have different text then it is easier to see how search works and even better if it is real english and not lorum ipsum

This website has numerous real text that can be used
https://www.blindtextgenerator.com/lorem-ipsum

**Comment by chmst** [comment]
You are right, It is a placeholder and hopefully will contain docu for using the modifier classes. At least I have learnt now how to expand :) the sample data

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
Am merging into the development branch for now. For further improvements please make pull requests against the [development](https://github.com/joomla/cassiopeia/tree/development) branch.

**Pull request merged**
