### PR TITLE
Fix colour themes

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for [https://github.com/joomla/cassiopeia/pull/58](https://github.com/joomla/cassiopeia/pull/58).

### Summary of Changes

- Add new scss files to css build script so that css and css.min will be built.
- Correct typo "autumm" to "autumn" in file name, language string names and value.
- Change "color" (en-US) to "colour" (en-GB) in language string values (but keep en-US language in the variable names because in CSS also "color" is used).

### Testing Instructions

- Code review.
- Test that `npm run build:css` or `npm ci` builds the css and css.min files for the 4 color themes.
- Check that the color themes option still works.

### CODE REVIEW

**Comment by brianteeman** [comment]
thank you

**Comment by richard67** [comment]
@drmenzelit Please check and if ok merge, or ping me and I merge. Thanks in advance.

**Comment by richard67** [comment]
@brianteeman Question: Should the option labels, e.g. `TPL_CASSIOPEIA_COLOR_NAME_AUTUMN="Autumn colours"`, in the list field be capitalited, e.g. `TPL_CASSIOPEIA_COLOR_NAME_AUTUMN="Autumn Colours"`?

**Comment by brianteeman** [comment]
As the label is called "Colour Theme" there really is no need to say anything more than "Autumn" in the option

**Comment by richard67** [comment]
Will merge this into PR #58 as I have premission of the author of the target PR (we talked on Glip).

**Pull request merged**
