### PR TITLE
Metismenu - Fix dropdown toggle for parent menu items with links

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

When using a menu item of a type which has a link as a parent for a dropdown, the metismenu js toggles the aria-expanded properties and expands and collapses the dropdown then clicking on the menu item's link and not when clicking on the dropdown toggle.

This PR corrects that by using the `triggerElement` parameter when creating the metismenu.

With help of the same parameter it was also possible to change the dropdown toggle from a linke with role="button" to a real button element.

Thanks to @bembelimen and @hans2103 for help with it.

### Testing Instructions

1. Checkout the [development branch](https://github.com/joomla/cassiopeia/tree/development) in your Cassipeia local git clone and if necessary pull the latest changes.

2. If never done before:
- Run `composer install` and `npm ci`.
- Install Blog Sample data.

3. In the "Main Menu Blog", change the type of those menu items which have sub-menu items from "Menu Heading" to something else which has a link, e.g. "Featured Articles".

4. Check the dropdown toggle of the metismenu in frontend (= horizontal menu in the header area).
Result: See section "Actual result" below.

5. Apply the chages of this PR.

6. Run `npm run build:css` or `npm ci` to compile css.

7. Check again the dropdown toggle of the metismenu in frontend.
Result: See section "Expected result" below.

8. Inspect the menu's markup with browser tools.
Result: See section "Expected result" below.

### Expected result

The dropdown toggles when clicking the dropdown toggle.

When clicking on the menu item's link, the corresponding page is shown.

A `<button>` element is used for the dropdown toggle.

### Actual result

The dropdown toggles when clicking on the menu item's link and not when clicking on the dropdown toggle.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Please have the accessibility team check this as I am fairly certain that role=button is not correct

**Comment by richard67** [comment]
@chmst Could you ask them to check?

**Comment by richard67** [comment]
@hans2103 I think we will need some additional js for making the aria-expanded of a menu item link with a dropdown change, too, when the dropdown is toggled. Currently only the aria-expanded ot the dropdown toggle "button" (which is not a button, I know) changes. If we need additional js anyway, maybe we can also handle a real button element somehow?

**Comment by chmst** [comment]
I have tested recent changes and it looks good. With keyboard the focus is set as  expected.

**Comment by hans2103** [comment]
Nice fixes from @bembelimen 
Using the MetisMenu initiator to point to the triggerElement to solve the tab order

**Comment by richard67** [comment]
In my test here the aria-expanded only changes to true for the dropdown toggle but not for the menuitem link or text when the dropdown is expanded.

@chmst Does it really need the "aria-expanded" attribute on the menuitem link or span in addition to the dropdown toggle link?

And is the "aria-haspopup" set in the right way nop?

Maybe check together witn @hans2103 . He found examples where the "aria-expanded" attribute was used and was toggling on both, the menu item link (or span if no link) and the dropdown toggle.

**Comment by hans2103** [comment]
@chmst the article @richard67 refers to: https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavkbbtn

**Comment by richard67** [comment]
Now it's using a button and not a link for the dropdown toggle.

@chmst Could you review this PR with the GitHub review functionality and test, too? It requires 1 review before it can be merged into the development branch.

**Comment by hans2103** [comment]
Tested successfully

**Comment by chmst** [comment]
Tested successfully.

**Comment by brianteeman** [comment]
Can I ask why this is done as a template override and not as a general layout option for the menu module?

You still might need some css just for cassiopeia but the menu layout would be usable by everyone no matter the template.

I really think it is wrong to ever have an override in a core template

**Comment by richard67** [comment]
> Can I ask why this is done as a template override and not as a general layout option for the menu module?

@chmst @drmenzelit @hans2103 What do you think? Shall we do that? Makes sense to me.

**Comment by bembelimen** [comment]
> Can I ask why this is done as a template override and not as a general layout option for the menu module?
> 
> You still might need some css just for cassiopeia but the menu layout would be usable by everyone no matter the template.
> 
> I really think it is wrong to ever have an override in a core template

The reason is, that otherwise every 3rd party template has to implement the Metis menu, because it's always in the list of the layouts (and not linked to this template)

**Review by chmst — APPROVED** [review]

**Comment by ciar4n** [comment]
> The reason is, that otherwise every 3rd party template has to implement the Metis menu, because it's always in the list of the layouts (and not linked to this template)

Maybe just override the default layout in the template using metismenu? This still leaves the current default layout not functional in any usable way in the 'menu' position.

**Comment by brianteeman** [comment]
@bembelimen 
> The reason is, that otherwise every 3rd party template has to implement the Metis menu, because it's always in the list of the layouts (and not linked to this template)

That is why I am asking for it NOT to be an override. What you have described is exactly what this PR does not do.

**Comment by richard67** [comment]
@brianteeman This PR here does nothing beside modifying the solution which was implemented with a previous one here in this development. It is not this PR which adds the metismenu.

**Comment by brianteeman** [comment]
My comments are still valid

**Comment by richard67** [comment]
Read the title: It fixed the dropdown toggle, nothing else.

**Comment by richard67** [comment]
We can open a new issue for @ciar4n suggestion.

**Comment by richard67** [comment]
> What you have described is exactly what this PR does not do.

@brianteeman They might be valid regaring the usage of metismenu but not regarding this PR because as the title of this PR says it is not scope of this PR. So the part of the comment cited above is definitely wrong.

**Comment by richard67** [comment]
@brianteeman Thanks for opening the issue.

**Pull request merged**
