### PR TITLE
Remove the white border on active pagination elements

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #107.

### Summary of Changes

This PR removes the white border on active pagination elements.
Removing grey border on disabled elements has consequences for disabled page-links as well. 

### Testing Instructions

- Joomla 4 with Testing Sample Data
- Go To /index.php/article-category-list
- Apply patch
- `npm run build:css`
- Notice borders around all pagination items

### Expected result

Schermafbeelding 2020-09-24 om 22 20 31

### CODE REVIEW

**Comment by richard67** [comment]
@hans2103 I don't think the title of this PR was intended to be "Merge branch 'cassiopeia/4.0-dev' into feature-cassiopeia/4.0-dev".

**Comment by Quy** [comment]
Per screenshot, the first and last buttons should not have inner rounded corners.

**Comment by hans2103** [comment]
True... Something went wrong. Going to bed now and will fix in the morning.

**Comment by richard67** [comment]
I've fixed the PR title.

**Comment by hans2103** [comment]
closing to make a new one.... I see that I also got the wrong branch on my forked repo

**Pull request closed without merging**
