### PR TITLE
Remove *.* selector from _forms.scss

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #106 .

### Testing Instructions
Run npm ci or compile scss

Check all forms present on the page after login on frontend.
Check a compact list of tags (create a menu item for this)

### Expected result
The buttons on a compact list of tags are aligned
Other forms are not affected and the spacing between fieldsets and between elements inside a fieldset is still correct.
grafik

### Actual result
The buttons on a compact list of tags are not aligned

### CODE REVIEW

**Review by hans2103 — APPROVED** [review]

**Comment by brianteeman** [comment]
Can we please not use derogatory terms in the pull requests. They become part of the history of Joomla. Thanks

**Comment by drmenzelit** [comment]
Sorry, I thought it is a common name for the *.* selector

**Comment by hans2103** [comment]
> Sorry, I thought it is a common name for the _._ selector

me too
I've got this term from Heydon Pickering as mentioned in article [Axiomatic CSS and Lobotomized Owls
](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/)

**Comment by hans2103** [comment]
This is what I see. I think the dropdown is too wide.
Schermafbeelding 2020-09-30 om 19 33 54

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/30813

Where I propose a refactoring of the filters for contact list, and, if accepted, to be also used for articles list and normalized for tags list. Basically add a Clear button and use text instead of icons.

**Comment by infograf768** [comment]
@hans2103 
I can't reproduce your issue.

**Comment by richard67** [comment]
@hans2103 Maybe your development branch is outdated? How are you testing?

**Comment by chmst** [comment]
The pr of @infograf768 looks very promising - it could resolve all the filtering issues.  #154 too.

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.
- I could reproduce the issue.
- I can confirm it is solved when this PR is applied and `npm ci` has run.
- I can't confirm @hans2103 's finding with the too wide dropdown for the list limit.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
