### PR TITLE
[Metismenu] [WiP] Separate link or text and button for dropdown items and clean up sub-layouts

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

WiP - work in progress.

- Move dropdown handling to main layout override
- Remove obsolete sub-layout overrides
- Dropdown items with link and dropdown "button".

### Testing Instructions

Checkout the branch, pull the latest changes and run "npm ci".

### Expected result

Dropdown should work the same way as without this PR, but now you should be able to use any type of menu item for a parent, and not only "Header" items, and depending on the item type there is a link for navigation.

### Actual result

Dropdowns work only with  "Header" items, there is no link for navigation possible beside the one for opening and closing the dropdown.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@hans2103 This is what I have right now. I could not use a button for the dropdown "button" because the metismenu js expects it to be a link for opening and closing the dropdown on click. The scss needs to be adapted to my changes. I think it will even become easier because what now is `.metismenu.mod-menu > li > a.has-arrow::after` will become `.metismenu.mod-menu > li > a.has-arrow`. But I don't have the time now to fix the scss, and I'm not very good in it either. Could you have a look and propose the necessary changes e.g. with a pr agains my branch, or just some code snippet here or on Glip? Thanks in advance.

**Comment by N6REJ** [comment]
is there some reason we're calling it .has-arrow when .caret is the defacto class?

**Comment by richard67** [comment]
@N6REJ What does that have to do with this PR here? Nothing.

**Comment by richard67** [comment]
@N6REJ "has-arrow" comes from metismenu and is used by the js to open and close the dropdown, so I haven't invented that, I only have moved that from the sub-layouts to the main layout so the sub-layouts became obsolete.

**Comment by chmst** [comment]
@N6REJ .has-arrow is a js selector. So no idea to toch this name.

**Pull request merged**
