### PR TITLE
[blog sample data] New attempt with different images.

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #4 .

### Summary of Changes

- Re-Added lost lead typograpy in the language file.
- Removed duplicate comment
- Remove superfluous image params.
- Add the new param for _alt_empty to most of the images - @brianteeman 
- Add alt text to two images

Add different images from the nasa imagery (including a backlink). Images are cut and size is optimised.  

### Testing Instructions
Install the blog sample data on a fresh joomla. 

### Expected result
kind of that:

grafik

### Actual result
Only one image (the banner is used everywhere)

### Documentation Changes Required
screens maybe

### CODE REVIEW

**Comment by richard67** [comment]
@chmst You set the new "alt empty" flag to 1 in sample data for the articles' intro and full text images. Is that right?
@brianteeman What do you think?

**Comment by brianteeman** [comment]
They are decorative so its ok but it would be nice to have an example in the sample data set that uses an alt description.

This is a useful guide to when an image is decorative etc https://www.w3.org/WAI/tutorials/images/decision-tree/

**Comment by chmst** [comment]
Text data are always work for translators. But I have added two very short sample alt texts.

**Review by drmenzelit — APPROVED** [review]

**Review by bembelimen — APPROVED** [review]
If we're allowed to use the images license-wise, then it's good to go.

**Comment by richard67** [comment]
@drmenzelit @bembelimen Your approval was based on code review (which is fine and sufficient for an approval)? Or did you also do a real test?

**Comment by drmenzelit** [comment]
Only code review this time

**Review by hans2103 — APPROVED** [review]

**Comment by hans2103** [comment]
code review

**Review by richard67 — APPROVED** [review]
Last changes fix the issues I've found.

**Comment by richard67** [comment]
Funny that 3 previous reviewers haven't found it.

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
