### PR TITLE
[Use local Google Fonts] [DRAFT] Google fonts list

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
Will populate the google fonts list by pulling the api of current fonts.

### Documentation Changes Required
Will require explanation of its use.

### CODE REVIEW

**Comment by richard67** [comment]
It seems there is something wrong with this PR. It is maybe based on the wrong base branch, or the branch was not up to date. If you look on the changes on GitHub you see e.g. the old switch case coming back for the loading of the css.

**Comment by N6REJ** [comment]
@richard67 I created the branch from google fonts pr.  Maybe I did it too early?
So far this is just a start.

**Comment by richard67** [comment]
@N6REJ I've updated your branch on GitHub for thiy PR to the latest changes in the base branch. To see that locally in your IDE you have to pull the changes. Please check the change on GitHub if something is missing. As far as I can see you add a new form field, but it's not used anywhere yet.

**Comment by N6REJ** [comment]
re: field, yes, I'm way out of my element right now so I'm struggling.. so far all I did was try to migrate the list field into a new "fonts" field, as the list view is good enough for basic usage.  It can always be enhanced later.
my thought process is...
create "fonts" form field
  This field will present the list of google fonts that were available as of last build time.
  it will do this by using the xml file generated during build.  ( could be during install ) 
at first ( or maybe forever ) it will only support google fonts.

**Comment by N6REJ** [comment]
@richard67 TY !!  I've pulled all the changes to local.

**Comment by brianteeman** [comment]
> This field will present the list of google fonts that were available as of last build time.

You do realise that this list will be 1000 rows

**Comment by richard67** [comment]
We should only list the fonts for which we have a local (s)css file, i.e. in the target branch of this PR currently "josefin-sans" and "montserrat". It should work similar like the selection of available module layouts from the template.

I haven't checked the code of this PR here yet what it does.

@N6REJ Maybe you can describe it in a few words.

**Comment by richard67** [comment]
At the end all we need is to go through all "*.css" files in folder "templates/cassiopeia/css/fonts" (which is not in the sources but will be build by "npm run compile:css" or "npm ci") and get the base name of each file to build the list of available local fonts for the dropdown select.

This would save us from having to edit the xml file to add new options.

We still would have to download and locally store the fonts manually.

To replace that manual procedure by using dependency management (e.g. node) is another task then.

**Comment by N6REJ** [comment]
> At the end all we need is to go through all "*.css" files in folder "templates/cassiopeia/css/fonts" (which is not in the sources but will be build by "npm run compile:css" or "npm ci") and get the base name of each file to build the list of available local fonts for the dropdown select.
> 
> This would save us from having to edit the xml file to add new options.
> 
> We still would have to download and locally store the fonts manually.
> 
> To replace that manual procedure by using dependency management (e.g. node) is another task then.

I like your way better.. it's more flexible.  Are you able to make that happen?
@brianteeman yeah, I know... wasn't planning on it doing that pull in front end.

**Comment by richard67** [comment]
@N6REJ I plan to do so, but it might be weekend until I have something testable because private stuff and regular job keep me busy.

**Comment by richard67** [comment]
Hmm, I just see we would still have to add the fonts manually to the assets list `templates/cassiopeia/joomla.asset.json`.

**Pull request closed without merging**
