### PR TITLE
Change to navbar-expand-md

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #86 .

### Summary of Changes
Changed navbar-expand-lg to navbar-expand-md to have the same media query for hamburger menu and for the switch from horizontal to vertical in the top menu

### Testing Instructions
Install patch, no npm needed

### Expected result
When hamburger menu appears the menu items have a vertical layout

### Actual result
Hamburger menu -> menu still horizontal

### CODE REVIEW

**Review by hans2103 — APPROVED** [review]
tested and reviewed... both look good

**Comment by richard67** [comment]
There is something wrong.

The following screenshots show from top to botton ongoing reduction of width, using Firefox screen size simulator. The sizes are shown at the top in the control field.









As you can see, the search module is still right beside the (now with this PR vertical) menu => OK.

Reducing width more, the search module goes below the menu => OK.

Reducing width more, the search module goes back to right beside the menu => ???

Reducing width more, the search module goes back to below the menu => OK.

**Comment by chmst** [comment]
There seems to be only one solution which works always: 
Change the ordering - show first the search form, then the menu. What do you think?

**Comment by drmenzelit** [comment]
@richard67 can you please test the last commit?

**Comment by richard67** [comment]
@drmenzelit Yes, it solves the issue.

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
