### PR TITLE
Add Metismenu to Cassiopeia

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #9 .

### Summary of Changes

This pull resuest (PR) adds a new layout for an accessible frontend menu with dropdowns using [metismenujs](https://github.com/onokumus/metismenujs) to the Cassiopeia template of Joomla 4.

Metismenujs is a vanilla js variant of metismenu, i.e. it doesn't depend on jquery.

It is acessible and responsive and provides pull-downs.

We use it already in the backend in the Atum template, so using it in Cassiopeia, too, doesn't cause a new external dependency.

### Testing Instructions

Apply the changes in this PR to a clean, current 4.0-dev branch and then run `npm ci`.

...

(will be completed soon)

### Expected result

Metismenu available and it works in Cassiopeia.

### Actual result

No menu with dropdowns available in Cassiopeia.

### Documentation Changes Required

To be specified.

### CODE REVIEW

**Comment by richard67** [comment]
I don't understand yet why we need those files (are these sub-layouts?) `metismenu_component.php`, `metismenu_heading.php`, `metismenu_separator.php` and `metismenu_url.php`. Couldn't we handle it all in `metismenu.php`?

I know the admin menu does it like that, but maybe we can simplify that for the frontend?

**Comment by ciar4n** [comment]
With https://github.com/joomla/cassiopeia/pull/26/commits/b0b7b2c9ade1e07ed0f10707115861abfb85149d

captured-2

**Comment by chmst** [comment]
Question:  

Is it possible to have a menu item AND a drop-down arrow in one menu item? This means two links on one line. 
The user then must see that there are two links.
We must be sure that this is announced correctly by a screenreader.

**Comment by richard67** [comment]
Could someone have a look on [https://github.com/joomla/cassiopeia/pull/37#issuecomment-678671202](https://github.com/joomla/cassiopeia/pull/37#issuecomment-678671202)?

**Comment by richard67** [comment]
This Pull Request (PR) is continued together with PR #41 in the new PR #46 . Please continue tests and feedback and discussions there.

**Pull request closed without merging**
