### PR TITLE
Remove the white border on active pagination elements

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue #107.

### Summary of Changes

This PR removes the white border on active pagination elements.
Removing grey border on disabled elements has consequences for disabled page-links as well. 

### Testing Instructions

- Joomla 4 with Testing Sample Data
- Go To /index.php/article-category-list
- Apply patch
- `npm run build:css`
- Notice borders around all pagination items

### Expected result

Schermafbeelding 2020-09-24 om 22 20 31

### CODE REVIEW

**Comment by drmenzelit** [comment]
It is intended to have rounded corners left and right on first and last element?

**Comment by hans2103** [comment]
> It is intended to have rounded corners left and right on first and last element?

I don't know... not the designer. :-)
But...commit https://github.com/joomla/cassiopeia/pull/131/commits/0f4799100ae2f97c6bc28a44aa98aa8db2678f69 fixes the border radius on first and last child

**Comment by hans2103** [comment]
https://github.com/joomla/cassiopeia/pull/131/commits/d0fccf6bf421c5fcaaa7e52a8bb62a4010c07552 removes radius, since it is already set

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

**Comment by chmst** [comment]
Tested with success for the border .

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
