### PR TITLE
Change positions

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Swap position main-top and breadcrumbs

### Actual result

grafik

### CODE REVIEW

**Review by hans2103 — APPROVED** [review]

**Comment by richard67** [comment]
@hans2103 @chmst There is no space betwen the grey frame of the breadcrumbs module and the heading, while for the sidebar modules there is. Shall it be fixed with this PR here or with another, future one?

**Comment by hans2103** [comment]
fixed in https://github.com/joomla/cassiopeia/pull/132

**Comment by hans2103** [comment]
and relates to https://github.com/joomla/joomla-cms/pull/30760

**Comment by hans2103** [comment]
fixing missing spacing is not the scope of this issue

**Comment by richard67** [comment]
As I goot feedback on Glip from the team that this is commonly accepted and has been tested by a few people, I merge.

**Comment by richard67** [comment]
@chmst When testing PR #132 , I noticed that alerts are now shown below breadcrumbs and below main-top. Is that by purpose?

**Comment by chmst** [comment]
Yes. Alerts come always from components. So I think that it is better to have the messages above the component area.

**Comment by brianteeman** [comment]
It is a good change. Especially on a site with lots of modules before the component.

thanks

**Pull request merged**
