### PR TITLE
Updated the "Working on your site" article

### PR DESCRIPTION
**Pull request by ohrionmartin**
Pull Request for Issue #95 .

### Summary of Changes
Corrected the path to follow when installing a template in the working on your site article

### Testing Instructions

Apply sample data in a fresh installation of Cassiopeia

### Expected result

The new j4 way to install extensions (templates)

### Actual result

The "working on your site" article still displays the old way to do it.

### CODE REVIEW

**Review by chmst — APPROVED** [review]

**Comment by chmst** [comment]
thank you, @ohrionmartin!

**Comment by drmenzelit** [comment]
I have tested this PR successfully

**Comment by brianteeman** [comment]
Thanks for writing this. Could you please review the language style guide as it is very useful and should be applied here as well. Especially the words to watch section. This ensures that we are consistent in our terminology.

https://developer.joomla.org/en-gb-user-interface-text-guidelines/

Oh and please remove the references to "weblinks"

**Comment by ohrionmartin** [comment]
> Thanks for writing this. Could you please review the language style guide as it is very useful and should be applied here as well. Especially the words to watch section. This ensures that we are consistent in our terminology.
> 
> https://developer.joomla.org/en-gb-user-interface-text-guidelines/
> 
> Oh and please remove the references to "weblinks"

Alright, I'll do that and thank you for the feedback!

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
