### PR TITLE
Rocket image for sample data

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
An alternatve for sample images with the rocket image. 
The image could be made available as svg (and without the BETA text) and adapted to the base colour. 

We then need different formats. 

grafik

grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
To repeat what I just told a client
An image can be used to illustrate an event but any text on the image must also be displayed in the description.

**Comment by chmst** [comment]
At this moment, it is more about the appearance of the sample data site as a whole. 
If we know which images - I can add a description. 

And for making it easy for translators, I'd prefer als text a simple "Joomla 4"

**Comment by brianteeman** [comment]
yes we definitely dont want translators to have to change images

**Comment by brianteeman** [comment]
BTW what is the small joomla logo 
image

**Comment by richard67** [comment]
> BTW what is the small joomla logo
> image

Good question. It looks like the one normally shown at the left hand side of the debug bar at the bottom when "Debug System" is switched on. But I don't have that here when testing.

**Comment by chmst** [comment]
Finally found - if the debugger is on, the firefox screenshot shows it there. No clue why.

**Comment by chmst** [comment]
This is no improvement, closing now

**Pull request closed without merging**
