### PR TITLE
Merge with upstream

### PR DESCRIPTION
**Pull request by ohrionmartin**

### CODE REVIEW

**Comment by richard67** [comment]
@ohrionmartin What are you doing here?

**Comment by ohrionmartin** [comment]
@richard67 
I am sorry, I wanted to update my fork with the Upstream and the repositories were supposed to be the other way around in in PR.
I will close this PR.

**Comment by richard67** [comment]
The development in this repository has been finished, and the result has been merged in the CMS repository: https://github.com/joomla/joomla-cms/pull/31520 .

So there is no need to do anything with this repository here, neither the one or the other way ;-)

**Comment by ohrionmartin** [comment]
Ok, thanks for the info!

**Pull request closed without merging**
