### PR TITLE
[RFC Add weights to fonts schemes names

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

Shall we do that?

### Testing Instructions

Apply the changes of this PR.

### Expected result AFTER applying this Pull Request

2020-11-30_fonts-schemes-idea-3

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Only if you explain when its 700 and when its 400

eg Fira Sans (headings 700 body 400) 

or something like that

**Comment by richard67** [comment]
@brianteeman Then we might need to make it translatable strings. Or can we still hard-code it like now?

**Comment by richard67** [comment]
Right now, always headings comes first in the name, then body.

**Comment by brianteeman** [comment]
it all depends if you want users to be mind readers and good at guessing or not. Especially if you dont know any css then the numbers are meaningless

**Comment by richard67** [comment]
@brianteeman How about this?

2020-11-30_fonts-schemes-idea-2

A bit long, but I'd like to keep the "local" and "web" somewhere so people can see where their fonts come from without having to open the dropdown.

And do you think we should make it translatable? The more we add, the more it might be weird with RTL.

**Comment by richard67** [comment]
Or maybe better:

2020-11-30_fonts-schemes-idea-3

**Comment by brianteeman** [comment]
>, but I'd like to keep the "local" and "web" 

I wondered why you had that. I see your logic but not sure I see the need

> do you think we should make it translatable?

Probably - but obviously not the font name

**Comment by richard67** [comment]
> Probably - but obviously not the font name

@brianteeman Then we can only make a comment in the language file not to translate these words in the string, or we have to create an own custom field where we use an sprintf. For not I think we leave it hard-coded.

**Comment by richard67** [comment]
Closing as the work in this repository here has been finished, and the result has been merged with https://github.com/joomla/joomla-cms/pull/31520 in the CMS repository.

If necessary we can come back to what's done in this PR here with a PR in the CMS repository.

**Pull request closed without merging**
