### PR TITLE
Replace template_thumbnail for cassiopeia

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #174 .

### Summary of Changes
A new screen of the new cassiopeia layout

### Testing Instructions
Apply the patch and see the template in the backend
grafik

with Preview
grafik

### Actual result
Tumbnail of the first version of cassiopeia

### Documentation Changes Required 
yes, screenshots.

### Note 
Designer's Help would be highly appreciated

### CODE REVIEW

**Comment by brianteeman** [comment]
The image is fine but you need to resize and compress it to 640x480
AND create a template_thumbnail.png of 200x150

**Comment by richard67** [comment]
@chmst If you will change colours in PR #227 e.g. due to review comments, you will have to make new thumbnail images in this PR here, because this PR here shows the colouring resulting from PR #227 .

So I suggest to wait with implementing [Brian's comment above](https://github.com/joomla/cassiopeia/pull/226#issuecomment-723676742) until PR #227 is finally merged.

**Comment by chmst** [comment]
Template thumbnail and template preview added. Help of a designer for better presentation would be highly appreciated.

**Comment by brianteeman** [comment]
Looks good to me

**Comment by richard67** [comment]
@brianteeman Is it ok that the new images are 600x400 and 200x142 instead of 640x480 and 200x150? And is it ok that the preview shows a different image than the thumbnail? I'm not sure with that, so I thought maybe I should ask you.

**Comment by richard67** [comment]
I see Protostar also has different sizes than 640x480 and 200x150 and different images for thumbnail and preview, so that should be ok here, too.

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

Well done, looks really good.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
