### PR TITLE
[Metismenu] Horizontal metismenu at other places than the header section and other improvements

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issues #91 and #230 .

### Summary of Changes

This pull request (PR) implements following improvements for the metismenu module:

1. Add a new CSS class "level-`n`" to the menu item (`li` element) with `n` being the menu item's level relative to the starting level, i.e. top item has `level-1`, submenu item blow that has `level-2` and so on.
This allows individual styling of menu items depending on their level and allows to simplify SCSS specific for the `header` block, see point 3.
2. Add SCSS for forcing a horizontal menu by adding module class `menu-horizontal` in the metimenu module's advanced settings.
This allows to have horizontal metismenu at other module positions than those in the `header` block.
3. Simplify SCSS by moving the header-specific styling to the _header.scss file and having extra styling for the top level menu items with use of point above so the styling for others can be put together.
4. Add a new CSS class to dropdown toggle buttons to be able to distinguish the two possible types of these buttons. This helps with solving the next point 5.
- Small, separate dropdown toggle button for menu items with a link, i.e. component or URL, get CSS class `mm-toggler-link`.
- Big dropdown toggles for menu items without a link, i.e. heading or separator, where the button is the complete item, get CSS class `mm-toggler-nolink`.
5. Fix issue #230 .
6. Add some CSS styling specific for the footer section so a metismenu can be used with the white text colour enforced for that section. This point could be improved with a later PR.

#### Preparation

1. If you have a development environment for Joomla 4, i.e. a git client and composer and npm, checkout the [development-metismenu-horizontal](https://github.com/joomla/cassiopeia/tree/development-metismenu-horizontal) branch, pull the latest changes, run "composer install" and "npm ci", and then make a new installation.
If you don't have that, use the following package to make a new installation: _(Obsolete link removed.)_

2. Login to backend and install "Blog Sample Data".

3. Modify the "Main Menu Blog" so that it has a deeper structure.
The easiest way to do that is to copy the "Sample Layouts -> Articles" item to another menu, using the batch function, and then move the copy from that other menu to the "Sample Layouts -> Articles -> Joomla" item, so you have something like this:

4. Modify the "Main Menu Blog" so that it contains both kinds of parent menu items at the top level, i.e. that in addition to the heading item "Sample Layouts" there is another one, also being a parent item but having a link.
The easiest way to do that is to copy the "Sample Layouts" menu item to another menu, using the batch function, then changing the menu item type of the copy "Sample Layouts (2)" to a type which has a link, e.g. a category blog, and then moving it back to the "Main Menu Blog", so you have something like this:

5. Make sure that you have some submenu item which is also a parent item and which doesn't have a link, so that you have both kinds of parent menu item in a submenu.
The easiest way to do that is to change the menu item type of one of the copies of "Sample Layouts -> Articles" from "category Blog" to a heading or a separator.

6. Now go to modules and make several copies of the "Main Menu Blog" module. Publish these copies at different module positions, e.g. "top-a", "breadcrumbs", "main top", "sidebar-left" or "sidebar-right" and "footer".

#### Tests

1. With desktop screen size, verify spacing between menu items at the top level of the metismenu in the header section.
Result: Spacing between parent menu items and non parent menu items is the same, regardless of the type of the menu item (with or without a link).

2. Verify the underlining of the top level parent menu item with a link in the metismenu in the header section.
Result: Link and dropdown toggle are underlined separately, and there is sufficient distance between the lines to see that.

3. Verify that vertical metismenus continue to work as before on the same position.

4. Add the module class "menu-horizontal" to all metismenus:

and check the results:
- For the metismenu in the header section there is no change in look and behaviour.
- Horizontal metismenus at positions `sidebar-left` and `sidebar-right` look ugly, but that's a won't fix maybe.
- Horizontal metismenus at other positions look ok.

5. Check ow the metismenus at different positions look with different module styles like "card", "noCard" and others.

7. Change to RTL direction e.g. by changing `<rtl>0</rtl>` to `<rtl>1</rtl>` in file `language/en-GB/langmetadata.xml`.

8. Repeat steps 1, 2, 4 and 5.
Result: The menus look the same, just in the other direction.

### Actual result BEFORE applying this Pull Request

Spacing between menu items at the top level is not the same for normal menu items and parents for a metismenu in the header section at desktop screen size, see issue #230 , and the separate underlines of the link and the dropdown toggle for a menu item with link (see "Sample Layouts (2)" below) are hard to see:

Metismenus at other places than the module positions `menu` and `search` in the `header` block are always vertical. Things like e.g. "nav-pills" will not work. E.g. on position `top-a`:

### Expected result AFTER applying this Pull Request

Spacing between menu items at the top level is the same now for normal menu items and parents for a metismenu in the header section at desktop screen size, i.e. issue #230 is solved, and the separate underlines of the link and the dropdown toggle for a menu item with link (see "Sample Layouts (2)" below) look better, too:

If no module class "menu-horizontal" has been set in the module's advanced options, a metismenu module behaves in the same way as it would do at the same module position without this PR, i.e. no change for non-mobile and mobile screen sizes.

If the module class "menu-horizontal" has been set in the module's advanced options:
- Metismenus at positions `menu` and `search` in the `header` continue to behave in the same way as without this PR.
- Metismenus at positions `sidebar-left` and `sidebar-right` look ugly, but that's maybe a won't fix because nobody would want to make a vertical menu in the sidebars.
- Metismenus at other places than those mentioned before have horizontal orientation on non-mobile screens. E.g. on position `top-a` or position `main-top`, where the `card` module style is used by default:

- Position `main-top` with `noCard` module style:

- The same with direction RTL:

- When reducing screen width to mobile size, the menu changes to vertical orientation in the same way as a menu on module positions in the `header`block already does without this PR., e.g. on position `main-top` with `noCard` module style:

- The same with direction RTL:

- Footer section vertical:

- Footer section horizontal:

A metismenu in the footer section might not be very useful. But it still can be "abused" to make a normal one-level only menu in the footer be horizontal. Currently that's not possible with the default menu layout.

### Further improvements to be done with a future PR

- Footer section: If the footer section could be made to expand in height automatically when a pulldown-menu opens, the pullown background could be set to transparent. Or we can manage to enforce normal colours like in pullodown of metismenu at other places and change the drop-downs to pop-ups, i.e. they open above the toggle, or whatever else which could make a metismenu usable in the footer.
- Right margin of dropdowns in deeper levels that 2 doesn't look good:

### Documentation Changes Required

The menu class "menu-horizontal" for the metismenu should be mentioned somewhere.

### CODE REVIEW

**Review by drmenzelit — APPROVED** [review]

**Comment by richard67** [comment]
@drmenzelit Have you only reviewed and approved? Or did you do also a real test? Just a question for the records, am ok with review only.

**Comment by drmenzelit** [comment]
I have tested this successfully

**Comment by chmst** [comment]
Tested successfully. Great work!

**Comment by richard67** [comment]
Thanks for reviews and testing.

**Pull request merged**
