### PR TITLE
Fix missing icon on language dropdown module

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #218 (solve only a part of the issue)

### Summary of Changes
Add font-weight to display Fontawesome icon on language module
Add background-color to the select to make it also visible in header

### Testing Instructions
Run npm run build:css

### Expected result
grafik

### Actual result
grafik

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

Fixes the issue with the icon not being show.

But it might need more styling for the language switcher, e.g. colours if you have it on position "search", or overflow of the dropdown when in layout "card".

**Comment by richard67** [comment]
Thanks!

**Comment by infograf768** [comment]
@drmenzelit 
> But it might need more styling for the language switcher, e.g. colours if you have it on position "search", or overflow of the dropdown when in layout "card".

Problem with z-index not applied. Example for card.

Screen Shot 2020-11-03 at 10 20 44

Solved (but still not nice enough because of the width of the dropdown) if module itself is set to `nocard`

Screen Shot 2020-11-03 at 10 40 32
.
Also, missing rtl tweeks.

**Comment by richard67** [comment]
@infograf768 Should maybe be commented in the still open issue #218 .

**Comment by infograf768** [comment]
Posted there to refer to this comment

**Pull request merged**
