### PR TITLE
New layout for metis submenus

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #91 .

### Summary of Changes
Change layout of submenus for metismenu. It works also if a metismenu is on the sidebar

### Testing Instructions
Run npm

### Expected result
The submenu slides under the parent item.

grafik

### Actual result
The submenu has an absolute position

### CODE REVIEW

**Review by chmst — APPROVED** [review]

**Comment by richard67** [comment]
@chmst Was this just an approval by code review or also a real test? Approval means only code review normally.

**Comment by chmst** [comment]
It was a real test. We still need a fix for  indenting submenus in rtl languages.

**Comment by richard67** [comment]
@chmst If you do a real test in addition to review, please make a comment so we can see that.

The needed fix for indenting submenus in rtl languages, is that covered by your issue #91 ? If not, please extend that issue or make a new one.

@drmenzelit Do you wanna fix the indention of submenus in rtl languages with this PR here, or will you make a new one?

**Comment by drmenzelit** [comment]
The indentation in rtl languages should be solved with my last commit

**Comment by Scrabble96** [comment]
Is there a build I can install to have a look at this? Thanks.

**Comment by richard67** [comment]
> Is there a build I can install to have a look at this? Thanks.

@Scrabble96 No. We don't have automatically prebuilt packages for pull requests (PR) in this repository, and I can't manually build packages for every PR whenever it changes. So it needs npm to compile the scss for being able to test this PR.

**Comment by Scrabble96** [comment]
Ah. Ok. Does this menu work on a touch screen to open a sub-menu if the parent is also a link?

**Comment by richard67** [comment]
@Scrabble96 As this PR here only changes styling on what we have worked up to now, you can test what we have worked up to now without this PR. You can find a link to an installation package in the testing instructions of PR #48 . Follow the testing instructions in that PR, i.e. after having installed the CMS you have to install **_blog_** sample data.

**Comment by Scrabble96** [comment]
I have installed the Dev package and added two more layers of menu items. One of the top level items (ABOUT US) has both an article page in its own right and also a sub-menu and a further sub-menu below that, along with a separator line which is rendered when there is no child item. Another top level item is 'SEPARATOR' which is only a separator but has an article in the next level.

On the Cassiopeia dev (Metis?) menu (which I have moved to position sidebarright) no dropdown appears for these two items on either hover or click.

I have also installed a menu override of my own creation which is rendered in pure CSS (except for the built-in JS to deal with 'collapse', etc.) which I was already working on to cover these issues. I have placed this is in the sidebar-left position. There is no hover (yet) but it works on both mouse-driven and tappable devices.

To view both, please visit [https://cassiopeia.websiteprep.co.uk](https://cassiopeia.websiteprep.co.uk) - IGNORE THIS

I would be interested in your comments. Thanks.

**Comment by richard67** [comment]
@Scrabble96 I've allowed myself to correct your link in your previous comment. The link text was set to the correct URL, but the link URL was not set, and so clicking the link lead to a 404.

**Comment by richard67** [comment]
@Scrabble96 I've just built an installation package for this PR here: (outdated link removed). So if you like, make again a new installation with that package and test again.

**Comment by Scrabble96** [comment]
> 
> 
> @Scrabble96 I've just built an installation package for this PR here: (outdated link removed). So if you like, make again a new installation with that package and test again.

Thank you. It will be a few days before I can do this as I have other projects on, but I'll do it a.s.a.p.

**Comment by drmenzelit** [comment]
@Scrabble96 I think something is wrong with your installation.
That is how metismenu on sidebar looks currently
grafik
And a separator can have a submenu and it works on click.

And that is how the new layout (this PR) looks like
grafik

**Comment by Scrabble96** [comment]
> 
> 
> @Scrabble96 I think something is wrong with your installation.
>
I will be installing the new full package @richard67 has just prepared.

**Comment by Scrabble96** [comment]
Hi. Just had time to get it set up and do a quick test. It looks fine except for one thing:

On the narrow screen drop-down version, the separator links that don't have an item in their own right (e.g. the 'Sample Layouts' item) should not have an underline that shows up on click or tap.

**Comment by richard67** [comment]
@Scrabble96 Is a known issue, see https://github.com/joomla/cassiopeia/issues/125 ... we are working on it.

**Comment by richard67** [comment]
New installation package for this PR is (outdated link removed).

**Comment by richard67** [comment]
New installation package for this PR is (outdated link removed).

**Comment by richard67** [comment]
New installation package for this PR is (outdated link removed).

**Comment by richard67** [comment]
New installation package for this PR is (outdated link removed).

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

**Comment by richard67** [comment]
Thanks!

**Comment by Scrabble96** [comment]
> 
> 
> New installation package for this PR is (outdated link removed).

Hi. I clicked the link and got this message:

The document name you requested (/Joomla_4.0.0-beta5-dev-Cassiopeia-Test-Full_Package_PR-175_2020-10-19_v1.zip) could not be found on this server. However, we found documents with names similar to the one you requested.

Available documents:

    /Joomla_4.0.0-beta4-dev-Cassiopeia-Test-Elvis-Design-Full_Package_2020-09-14.zip (common basename)
    /Joomla_4.0.0-beta5-dev-Cassiopeia-Test-Full_Package_2020-10-19_v2.zip (common basename) 

Please consider informing the owner of the referring page https://github.com/joomla/cassiopeia/pull/175 about the broken link.

**Comment by richard67** [comment]
@Scrabble96 As you can see, this pull request (PR) has been merged, so you can test it together with all other done work using the installation package linked in the testing instructions of our dummy PR for testing, https://github.com/joomla/cassiopeia/pull/48 .

**Pull request merged**
