### PR TITLE
Sampledata: Separate Metismenu, use real names for menu items

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
The intention of this PR is to make a separate Metismenu, with real words in Menu Items.
It lets the old menu Items untouched and makes testing easier for rtl by @infograf768.

Additionally some houskeeping was made, typos fixed, hard coded item_ids replaced by the correct ItemIds.

### Testing Instructions
Install blog sample data in a fresh installation 

### Expected result
The menu with metismenu looks like this, all links are correct. 

grafik

### Note
While working here I have found some other issues: 
#95 , #97,  #98

In sampleData the module chrome noCard is used for the newsflash module. If chromeNames are changed, this has to be updated

### CODE REVIEW

**Comment by brianteeman** [comment]
speaking names ??

**Comment by chmst** [comment]
Other than lorem ipsum .. it is too late for correct English :)

**Comment by brianteeman** [comment]
I knew it was a lost in translation problem I just couldnt work it out. "real words" would probably be correct ;)

**Comment by chmst** [comment]
Related issue https://github.com/joomla/cassiopeia/issues/95

**Comment by richard67** [comment]
@chmst Not sure if I'm available to do a complete review.

But what I've noticed is that the title "Metismenu" might be misleading.

It makes me expect to find some information about Metismenu below it (whatever that may be, a non dev user might think).

But that's not the case.

**Comment by richard67** [comment]
@chmst Is it by purpose that now the metismenu doesn't have anymore a parent item which has a link plus a dropdown toggle and again only have menu items of type "heading" as parent items?

**Comment by chmst** [comment]
@richard67 with these changes your RFC 104 is resolved. Our sample articles arenot good for masonry layout. 
Additionally I have added a link to the parent in the sample dropdown

**Comment by richard67** [comment]
@chmst What still confused me is that for 2 of 3 menu items in the pull down in the 3rd level, the titles and the corresponding article titles are different.
- Menu item "Joomla V4" shows article "Your Template" => ???
- Menu item "Millions of Websites" shows article "Multilingual" => ???
- Menu item "Flexible System" shows article "Flexible System" => OK

Another thing is that I'm not sure if we use the format "Joomla V4" anywhere in our publications. I remember only having seen "Joomla 4", "Joomla V4" I don't remember having seen it anywhere in official publications. But with this I might be wrong, my memory is good but not perfect.

**Comment by chmst** [comment]
The Category List is dammaged: https://issues.joomla.org/tracker/joomla-cms/29504

**Comment by richard67** [comment]
> The Category List is dammaged: https://issues.joomla.org/tracker/joomla-cms/29504

I guess that's not related to my previous comment, or is it? I was referring to the single article links on the 3rd level of the pulldown menu.

**Comment by chmst** [comment]
@thank you.

> 
> 
> > The Category List is dammaged: https://issues.joomla.org/tracker/joomla-cms/29504
> 
> I guess that's not related to my previous comment, or is it? I was referring to the single article links on the 3rd level of the pulldown menu.

No, it is not. is is referred to 
grafik

**Comment by chmst** [comment]
Thank you @richard67 I have changed the Item Menu names so that is is clearer.

**Comment by richard67** [comment]
@chmst When having set up a multilingual site, logging in with English backend language, installing blog sample data, loggin out from backend and in again with German language and installing blog sample data, step 1 fails with the error that a category has the same alias as another category within the same parent category. That was not the case when I've tested that with the development branch a while ago.

**Comment by ghost** [comment]
Screenshot_2020-09-24 Sampledata Separate Metismenu, use real names for menu items by chmst · Pull Request #96 · joomla cas

aslo = also

**Comment by chmst** [comment]
@richard67 have you installed a multilingual site? As language files in DE and EN have the same content, the category names  indeed are duplicates.

**Comment by richard67** [comment]
> @richard67 have you installed a multilingual site? As language files in DE and EN have the same content, the category names indeed are duplicates.

@chmst Yes, I have installed a multilingual site. The titles of other stuff is extended by the language code in brackets. It should be done the same way for categories.

**Comment by chmst** [comment]
I don't know why, but the category title "Joomla 4" cannot be used and results in errors. This needs investigation in the category model. For now I have changed "Joomla 4" to "Joomla"

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this PR :white_check_mark: with success.

**Pull request merged**
