### PR TITLE
template missing string

### PR DESCRIPTION
**Pull request by brianteeman**
This string is used in the admin interface

image

### CODE REVIEW

**Comment by drmenzelit** [comment]
I think, it will be better to make this PR against the core repository

**Comment by brianteeman** [comment]
I can do that of course but as its cassiopeia related I did it here.
@richard67 what is your preference

**Comment by richard67** [comment]
> I can do that of course but as its cassiopeia related I did it here.
> @richard67 what is your preference

Either way is ok for me and has its advantages and disadvantages.

I'd leave that decision to the team leads.

**Comment by brianteeman** [comment]
oh I thought you were the person for this template. you seem to be doing a v good job of leading

**Comment by richard67** [comment]
@brianteeman Oh no, @chmst and @drmenzelit are both team leads. I am just the maintainer, i.e. I care for the git and GitHub stuff, help with stuff where I can help and of course because we are too few, test and review wherever I can. I hope I did not act too much like a team lead because I think the two we have do a pretty good job.

**Comment by brianteeman** [comment]
ok - well I will close it here and re-open on the main repo

**Pull request closed without merging**
