### PR TITLE
[Metismenu] [Draft] Move metismenu from template to module and integrate js into build process

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issues #53 , [https://github.com/joomla/cassiopeia/pull/195#issuecomment-715308105](https://github.com/joomla/cassiopeia/pull/195#issuecomment-715308105), #208 and [https://github.com/joomla/cassiopeia/pull/210#issuecomment-718710233](https://github.com/joomla/cassiopeia/pull/210#issuecomment-718710233).

Alternative to PR #221 and #224 .

### Summary of Changes

This pull request (PR) moves the alternative layout for the metismenu from the Cassiopeia template to the menu module, so the metismenu becomes available for 3rd party templates, too.

Therefore it adds a css file which is loaded by the module and provides the basic functionality. Template builders only need to add own styling like it is now for "Normal" menus, too.

In addition it changes the name of the layout to something more meaningful than "metismenu" and adds a language string for a nice layout name for the layout selection in the menu module's advanced options.

The name of the js file which already had es6 syntax is changed to extension `.es6.js`, and the file is moved to the right place in the `build/media_source` folder so that it's transpiled and minified and put at the right place in the `media` folder by the build script.

Finally, missing doc block with copyright information has been added to the js file.

### Testing Instructions

If you have development environment for Joomla 4, checkout the [development-move-metismenu-from-template-to-module](https://github.com/joomla/cassiopeia/tree/development-move-metismenu-from-template-to-module) branch, pull the latest changes, run "composer install" and "npm ci", and then make a new installation.

If you don't have that, use the following package to make a new installation: (obsolete link removed)

After that, login to backend and install "Blog Sample Data" to see the metismenu being used in frontend.

Then, still in backend, check the available layouts in the advanced options of the "Main Menu Blog" module.

Last but not least, go to frontend and verify that the metismenu works as well as before. You can also duplicate it in backend to another module position, or create another metismenu, and check in frontend that those modules still work well.

Finally, verify that in folder `media/mod_menu/js` (below the Joomla root, not the template folder) the following transpiled and minified js files are there in addition to what is there without this PR:
- menu-metismenu.es6.js
- menu-metismenu.es6.min.js
- menu-metismenu.js
- menu-metismenu.min.js

### Actual result BEFORE applying this Pull Request

Layout selection in the menu module's advanced options:

The javascript file `templates/cassiopeia/js/mod_menu/menu-metismenu.js` to load the metismenus has es6 syntax but just a plain "js" file name extension. There is no minified file of it. The js linter will not run on that.

### Expected result AFTER applying this Pull Request

Layout selection in the menu module's advanced options:

The metismenu (one or more than one at a time) works as well as without this PR.

The  javascript file `build/media_source/mod_menu/js/menu-metismenu.es6.js` to load the metismenu can be checked by the linter and is transpiled and copied to the right place by the build script.

### Documentation Changes Required

The alternative layout should be described in the J4 documentation for the menu module instead of the Cassiopeia template, where it would have to be documented if this PR will not be merged.

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge This will need your acceptance before I will undraft it.

With what we have currently in this repo, the metismenu js is not linted and not transpiled and minified.

This PR here will fix that AND make the metismenu be an alternative layout of the menu module so it can be used by 3rd party templates, too, if they care for the necessary CSS themselves.

But it means a kind of new feature for a core module, that's why I think it needs your acceptance.

If it is not ok, the other way to integrate the js into the build process would be to move it to `build/media_source/templates/cassiopeia/js/mod_menu/menu-metismenu.es6.js`.

**Comment by brianteeman** [comment]
> But it means a kind of new feature for a core module, that's why I think it needs your acceptance.

do you mean its a new feature and we are in feature freeze
or
do you mean its a new feature having multiple views for a module

**Comment by richard67** [comment]
> do you mean its a new feature and we are in feature freeze
> or
> do you mean its a new feature having multiple views for a module

Multiple views for a module is standard. But I thought maybe one could consider a new alternative layout for an old core module to be a new feature.

**Comment by richard67** [comment]
I've meanwhile received feedback by @wilsonge on Glip.

There is no "new feature" policy to be applied here, so that's not the problem.

But the metismenu layout looks ugly on a standard Cassiopeia (i.e. like it is now without the CSS changes in this repository here) and is not usable. See here an example with testing sample data:

2020-11-02_metismenu-with-core-cassiopeia

If the (s)css for the metismenu could be separated from the template's (s)css into a separate css file loaded by the metismenu module so that it looks ok on a "normal" bootstrap 4 based template, then this approach here would be the best one.

@drmenzelit @hans2103 Do you think this can be done, separate css file for the metismenu?

If not, we have to leave the metismenu layout in the template and use my other PR #221 instead of this one here.

**Comment by richard67** [comment]
Closing in favour of #221 .

**Pull request closed without merging**
